export type CurrencyOption = {
	code: string;
	symbol: string;
	label: string;
};

// ISO 4217 list (commonly used active currencies). Symbols are best-effort and may repeat ($, etc.).
export const CURRENCY_OPTIONS: CurrencyOption[] = [
	{ code: "USD", symbol: "$", label: "US Dollar" },
	{ code: "EUR", symbol: "€", label: "Euro" },
	{ code: "GBP", symbol: "£", label: "British Pound" },
	{ code: "JPY", symbol: "¥", label: "Japanese Yen" },
	{ code: "AUD", symbol: "$", label: "Australian Dollar" },
	{ code: "CAD", symbol: "$", label: "Canadian Dollar" },
	{ code: "CHF", symbol: "CHF", label: "Swiss Franc" },
	{ code: "CNY", symbol: "¥", label: "Chinese Yuan" },
	{ code: "HKD", symbol: "$", label: "Hong Kong Dollar" },
	{ code: "SGD", symbol: "$", label: "Singapore Dollar" },
	{ code: "NZD", symbol: "$", label: "New Zealand Dollar" },
	{ code: "SEK", symbol: "kr", label: "Swedish Krona" },
	{ code: "NOK", symbol: "kr", label: "Norwegian Krone" },
	{ code: "DKK", symbol: "kr", label: "Danish Krone" },
	{ code: "PLN", symbol: "zł", label: "Polish Zloty" },
	{ code: "CZK", symbol: "Kč", label: "Czech Koruna" },
	{ code: "HUF", symbol: "Ft", label: "Hungarian Forint" },
	{ code: "TRY", symbol: "₺", label: "Turkish Lira" },
	{ code: "MXN", symbol: "$", label: "Mexican Peso" },
	{ code: "BRL", symbol: "R$", label: "Brazilian Real" },
	{ code: "ARS", symbol: "$", label: "Argentine Peso" },
	{ code: "CLP", symbol: "$", label: "Chilean Peso" },
	{ code: "COP", symbol: "$", label: "Colombian Peso" },
	{ code: "PEN", symbol: "S/", label: "Peruvian Sol" },
	{ code: "UYU", symbol: "$", label: "Uruguayan Peso" },
	{ code: "ZAR", symbol: "R", label: "South African Rand" },
	{ code: "EGP", symbol: "£", label: "Egyptian Pound" },
	{ code: "NGN", symbol: "₦", label: "Nigerian Naira" },
	{ code: "KES", symbol: "KSh", label: "Kenyan Shilling" },
	{ code: "GHS", symbol: "₵", label: "Ghanaian Cedi" },
	{ code: "MAD", symbol: "د.م.", label: "Moroccan Dirham" },
	{ code: "TND", symbol: "د.ت", label: "Tunisian Dinar" },
	{ code: "AED", symbol: "د.إ", label: "UAE Dirham" },
	{ code: "SAR", symbol: "﷼", label: "Saudi Riyal" },
	{ code: "QAR", symbol: "﷼", label: "Qatari Riyal" },
	{ code: "KWD", symbol: "د.ك", label: "Kuwaiti Dinar" },
	{ code: "BHD", symbol: ".د.ب", label: "Bahraini Dinar" },
	{ code: "OMR", symbol: "﷼", label: "Omani Rial" },
	{ code: "ILS", symbol: "₪", label: "Israeli Shekel" },
	{ code: "INR", symbol: "₹", label: "Indian Rupee" },
	{ code: "PKR", symbol: "₨", label: "Pakistani Rupee" },
	{ code: "BDT", symbol: "৳", label: "Bangladeshi Taka" },
	{ code: "LKR", symbol: "Rs", label: "Sri Lankan Rupee" },
	{ code: "NPR", symbol: "₨", label: "Nepalese Rupee" },
	{ code: "MMK", symbol: "K", label: "Myanmar Kyat" },
	{ code: "THB", symbol: "฿", label: "Thai Baht" },
	{ code: "VND", symbol: "₫", label: "Vietnamese Dong" },
	{ code: "IDR", symbol: "Rp", label: "Indonesian Rupiah" },
	{ code: "MYR", symbol: "RM", label: "Malaysian Ringgit" },
	{ code: "PHP", symbol: "₱", label: "Philippine Peso" },
	{ code: "KRW", symbol: "₩", label: "South Korean Won" },
	{ code: "TWD", symbol: "NT$", label: "New Taiwan Dollar" },
	{ code: "HKD", symbol: "$", label: "Hong Kong Dollar" },
	{ code: "KHR", symbol: "៛", label: "Cambodian Riel" },
	{ code: "LAK", symbol: "₭", label: "Lao Kip" },
	{ code: "MNT", symbol: "₮", label: "Mongolian Tögrög" },
	{ code: "RUB", symbol: "₽", label: "Russian Ruble" },
	{ code: "UAH", symbol: "₴", label: "Ukrainian Hryvnia" },
	{ code: "BYN", symbol: "Br", label: "Belarusian Ruble" },
	{ code: "KZT", symbol: "₸", label: "Kazakhstani Tenge" },
	{ code: "UZS", symbol: "so'm", label: "Uzbekistani Som" },
	{ code: "AZN", symbol: "₼", label: "Azerbaijani Manat" },
	{ code: "GEL", symbol: "₾", label: "Georgian Lari" },
	{ code: "AMD", symbol: "֏", label: "Armenian Dram" },
	{ code: "RON", symbol: "lei", label: "Romanian Leu" },
	{ code: "BGN", symbol: "лв", label: "Bulgarian Lev" },
	{ code: "HRK", symbol: "€", label: "Croatian Kuna (replaced by EUR)" },
	{ code: "RSD", symbol: "дин", label: "Serbian Dinar" },
	{ code: "MKD", symbol: "ден", label: "Macedonian Denar" },
	{ code: "ALL", symbol: "L", label: "Albanian Lek" },
	{ code: "ISK", symbol: "kr", label: "Icelandic Króna" },
	{ code: "ARS", symbol: "$", label: "Argentine Peso" },
	{ code: "BZD", symbol: "$", label: "Belize Dollar" },
	{ code: "BMD", symbol: "$", label: "Bermudian Dollar" },
	{ code: "BBD", symbol: "$", label: "Barbados Dollar" },
	{ code: "BSD", symbol: "$", label: "Bahamian Dollar" },
	{ code: "TTD", symbol: "$", label: "Trinidad and Tobago Dollar" },
	{ code: "JMD", symbol: "$", label: "Jamaican Dollar" },
	{ code: "DOP", symbol: "$", label: "Dominican Peso" },
	{ code: "GTQ", symbol: "Q", label: "Guatemalan Quetzal" },
	{ code: "HNL", symbol: "L", label: "Honduran Lempira" },
	{ code: "CRC", symbol: "₡", label: "Costa Rican Colón" },
	{ code: "NIO", symbol: "C$", label: "Nicaraguan Córdoba" },
	{ code: "PAB", symbol: "B/.", label: "Panamanian Balboa" },
	{ code: "BWP", symbol: "P", label: "Botswana Pula" },
	{ code: "MZN", symbol: "MT", label: "Mozambican Metical" },
	{ code: "ETB", symbol: "Br", label: "Ethiopian Birr" },
	{ code: "TZS", symbol: "TSh", label: "Tanzanian Shilling" },
	{ code: "UGX", symbol: "USh", label: "Ugandan Shilling" },
	{ code: "AOA", symbol: "Kz", label: "Angolan Kwanza" },
	{ code: "CDF", symbol: "FC", label: "Congolese Franc" },
	{ code: "XAF", symbol: "FCFA", label: "Central African CFA Franc" },
	{ code: "XOF", symbol: "CFA", label: "West African CFA Franc" },
	{ code: "XPF", symbol: "₣", label: "CFP Franc" },
	{ code: "MUR", symbol: "₨", label: "Mauritian Rupee" },
	{ code: "SCR", symbol: "₨", label: "Seychellois Rupee" },
	{ code: "MVR", symbol: "Rf", label: "Maldivian Rufiyaa" },
	{ code: "BND", symbol: "$", label: "Brunei Dollar" },
	{ code: "KGS", symbol: "с", label: "Kyrgyzstani Som" },
	{ code: "TJS", symbol: "ЅМ", label: "Tajikistani Somoni" },
	{ code: "LRD", symbol: "$", label: "Liberian Dollar" },
	{ code: "SLL", symbol: "Le", label: "Sierra Leonean Leone" },
	{ code: "ZMW", symbol: "ZK", label: "Zambian Kwacha" },
	{ code: "MWK", symbol: "MK", label: "Malawian Kwacha" },
	{ code: "BAM", symbol: "KM", label: "Bosnia-Herzegovina Convertible Mark" },
	{ code: "VUV", symbol: "Vt", label: "Vanuatu Vatu" },
	{ code: "WST", symbol: "T", label: "Samoan Tala" },
	{ code: "FJD", symbol: "$", label: "Fijian Dollar" },
	{ code: "PGK", symbol: "K", label: "Papua New Guinean Kina" },
	{ code: "XCD", symbol: "$", label: "East Caribbean Dollar" },
	{ code: "GYD", symbol: "$", label: "Guyanese Dollar" },
	{ code: "SRD", symbol: "$", label: "Surinamese Dollar" },
	{ code: "HTG", symbol: "G", label: "Haitian Gourde" },
	{ code: "BIF", symbol: "FBu", label: "Burundian Franc" },
	{ code: "RWF", symbol: "FRw", label: "Rwandan Franc" },
	{ code: "DJF", symbol: "Fdj", label: "Djiboutian Franc" },
	{ code: "SOS", symbol: "Sh", label: "Somali Shilling" },
	{ code: "LSL", symbol: "L", label: "Lesotho Loti" },
	{ code: "SZL", symbol: "L", label: "Eswatini Lilangeni" },
	{ code: "MGA", symbol: "Ar", label: "Malagasy Ariary" },
	{ code: "KPW", symbol: "₩", label: "North Korean Won" },
	{ code: "SHP", symbol: "£", label: "Saint Helena Pound" },
	{ code: "GIP", symbol: "£", label: "Gibraltar Pound" },
	{ code: "FKP", symbol: "£", label: "Falkland Islands Pound" },
	{ code: "ANG", symbol: "ƒ", label: "Netherlands Antillean Guilder" },
	{ code: "AWG", symbol: "ƒ", label: "Aruban Florin" },
	{ code: "CUP", symbol: "$", label: "Cuban Peso" },
	{ code: "CUC", symbol: "$", label: "Cuban Convertible Peso" },
	{ code: "KMF", symbol: "CF", label: "Comorian Franc" },
	{ code: "SBD", symbol: "$", label: "Solomon Islands Dollar" },
	{ code: "TOP", symbol: "T$", label: "Tongan Paʻanga" },
	{ code: "BTN", symbol: "Nu.", label: "Bhutanese Ngultrum" },
	{ code: "MOP", symbol: "MOP$", label: "Macanese Pataca" },
	{ code: "KYD", symbol: "$", label: "Cayman Islands Dollar" },
	{ code: "BOV", symbol: "BOB", label: "Bolivian Mvdol (index)" },
	{ code: "BOB", symbol: "Bs", label: "Bolivian Boliviano" },
	{ code: "VES", symbol: "Bs.", label: "Venezuelan Bolívar" },
	{ code: "SDG", symbol: "£", label: "Sudanese Pound" },
	{ code: "SSP", symbol: "£", label: "South Sudanese Pound" },
	{ code: "ERN", symbol: "Nfk", label: "Eritrean Nakfa" },
	{ code: "LBP", symbol: "ل.ل", label: "Lebanese Pound" },
	{ code: "YER", symbol: "﷼", label: "Yemeni Rial" },
	{ code: "IRR", symbol: "﷼", label: "Iranian Rial" },
	{ code: "AFN", symbol: "؋", label: "Afghan Afghani" },
	{ code: "SYP", symbol: "£", label: "Syrian Pound" },
	{ code: "DZD", symbol: "د.ج", label: "Algerian Dinar" },
	{ code: "BHD", symbol: ".د.ب", label: "Bahraini Dinar" },
	{ code: "LYD", symbol: "ل.د", label: "Libyan Dinar" },
	{ code: "IQD", symbol: "ع.د", label: "Iraqi Dinar" },
	{ code: "JOD", symbol: "د.ا", label: "Jordanian Dinar" },
];

export function findCurrency(code?: string) {
	if (!code) return undefined;
	return CURRENCY_OPTIONS.find((c) => c.code === code.toUpperCase());
}
